### ISSUE TITLE
Some User Agents to consider

### ISSUE THREAD

**Issue by gsempe** [arp242/isbot#3]
I may have encounter not filtered bot User Agents.
It's important to note that for RoleUp I filter only on user-agents.

- Jakarta Commons-HttpClient/3.1
- WhatsApp/2.20.61 i
- Mozilla/5.0 (compatible; theoldreader.com)

**Comment by arp242** [comment]
I think that WhatsApp one may actually represent a real person viewing the page through the WhatsApp client? I can't really confirm that at the moment though; Some more WhatsApp examples here: https://github.com/allinurl/goaccess/issues/808

Also need to check theoldreader, can be either the RSS fetcher (bot) or someone viewing it through their app (not a bot). Need to look at this later too to confirm.

I changed `Apache-HttpClient/` to just `HttpClient/`, so that one should be fixed now.

**Comment by gsempe** [comment]
Hi Martin,
I got these two user agents. The first one is probably to filter the second one... is just for the fun 

"Mozilla/5.0 zgrab/0.x"
"Mozilla/5.0/Firefox/42.0 - nbertaupete95(at)gmail.com"
