### ISSUE TITLE
How did you find the ARIN entity ids?

### ISSUE THREAD

**Issue by nrempel** [arp242/isbot#4]
For example: DO-13

I'm working on a similar tool in Rust and a source for this information would be valuable!

**Comment by arp242** [comment]
I recorded IPs that were detected by the User-Agent detection and used a script to group them by organisation, then I looked at some of the top ones to see if they belong to some hosting organisation that shouldn't really be used by browsers, rather than a residential address.

I don't have any of this any more, sorry. There are probably a bunch of others that could be added too.

You can mostly just find out the same if you get a list of top VPS providers and look up their IP ranges; some publish them on their website, others can be found just by searching RIPE, ARIN, etc.

Hope that helps.

**Comment by nrempel** [comment]
Thank you! That's helpful. I think using the user agent detection is a great starting point.
